workflows:
  ios-release:
    name: iOS Release Build
    environment:
      sdk: '>=3.8.0 <4.0.0'
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Установка зависимостей Flutter
        script: |
          flutter pub get
      - name: Очистка предыдущих сборок
        script: |
          flutter clean
      - name: Удаление флага '-G' из project.pbxproj
        script: |
          find . -name "project.pbxproj" -exec sed -i '' 's/-G//g' {} +
      - name: Сборка iOS-приложения без подписи
        script: |
          flutter build ios --release --no-codesign
      - name: Упаковка Runner.ipa в zip
        script: |
          cd build/ios/iphoneos
          zip -r Runner.ipa.zip Runner.app
    artifacts:
      - build/ios/iphoneos/Runner.ipa.zip


